# Use the official NGinx image as the base image
FROM nginx:alpine

# Copy the contents of the public folder to NGinx's default public folder
COPY ./public /usr/share/nginx/html

# Expose port 80 for NGinx
EXPOSE 80
